apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: digital-assistant
  namespace: assistant
  labels:
    app: digital-assistant
spec:
  hosts:
  - digital-assistant.mur-kc.kymatunas.shoot.canary.k8s-hana.ondemand.com
  service:
    name: digital-assistant
    namespace: assistant
    port: 8080
  gateway: kyma-system/kyma-gateway
  rules:
  - path: /*
    methods: ["GET", "POST", "PUT", "DELETE"]
    noAuth: true
